# SPDX-License-Identifier: Unlicense OR 0BSD

# - https://docs.github.com/pt/actions
# - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# - https://docs.github.com/pt/actions/learn-github-actions/workflow-syntax-for-github-actions

# This workflow will do a clean install of node dependencies,
# cache/restore them, build the source code and run tests across
# different versions of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nodejs-build

on:
  push:
    # branches: [ $default-branch ]
    branches:
      - main
  pull_request:
    # branches: [ $default-branch ]
    branches:
      - main

jobs:
  # build:
  nodejs-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [14.x, 16.x]
        # node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        # package.json -> szwacz-electron-boilerplate/package.json:
        working-directory: ./szwacz-electron-boilerplate/

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # package.json -> szwacz-electron-boilerplate/package.json:
        cache-dependency-path: 'szwacz-electron-boilerplate/package-lock.json'

    - run: npm ci

    - run: npm run build --if-present
      env:
        DEBUG: electron-builder

    #### npm test ______________________________________________________________
    #### Option A: no Headless CI System .......................................
    # - run: npm test

    #### Option B: Headless CI System ..........................................
    # @see http://elementalselenium.com/tips/38-headless
    # @see https://github.com/electron/electron/pull/21996/commits/98cb49bfc03be312d7747cc3818c9d035ce4dd5b
    # @see https://github.com/marketplace/actions/gabrielbb-xvfb-action

    - name: npm test (headless)
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm test
        # package.json -> szwacz-electron-boilerplate/package.json:
        working-directory: ./szwacz-electron-boilerplate/
