
# ARCHIVUM:        .github/workflows/05-electron.yml
# LICENTIAM:        Dominium publicum
# SPDX-License-Identifier: Unlicense
# DOCUMENTORUM:     Links:
#                     - https://docs.github.com/pt/actions
#                     - https://github.com/marketplace/actions/electron-builder-action
#                     - https://github.com/samuelmeuli/action-electron-builder/blob/master/action.yml

name: electron-action

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Directory where NPM/Yarn commands should be run
          # default: "." (no subdirectory)
          package_root: szwacz-electron-boilerplate/

# jobs:
#   dotnet-action:
#     runs-on: ubuntu-latest
#     name: Dotnet ${{ matrix.dotnet }} sample
#     strategy:
#       matrix:
#         # dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
#         dotnet: [ '5.0.x' ]

#     steps:

#       #### _____________________________________________________________________
#       # _[por-Latn]
#       # Passo comum em todo GitHub action: obtem uma cópia do repositório
#       # para máquina que esta rodando os testes
#       # [por-Latn]_
#       - uses: actions/checkout@v2

#       #### _____________________________________________________________________
#       # @see https://github.com/actions/setup-dotnet
#       # @see https://github.com/timheuer/aspnet-core-sample-deploy/blob/master/.github/workflows/build-and-deploy.yml
#       - uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: ${{ matrix.dotnet }}

#       - run: dotnet build programma-exemplum-dotnet.csproj

#       - run: dotnet test programma-exemplum-dotnet.csproj

#       # _[por-Latn]
#       # É possível usar GitHub actions para publicar pacotes, e isso envolve
#       # usar opões extras documentadas em https://github.com/actions/setup-dotnet
#       # A forma como variável NUGET_AUTH_TOKEN é salva pode requerer
#       # certos cuidados. Vide
#       # https://docs.github.com/pt/actions/security-guides/security-hardening-for-github-actions
#       #
#       # Caso seu projeto tenha relação com algo humanitário, colaboradores
#       # do HXL-CPLP podem ajudar nessa etapa.
#       # [por-Latn]_
#       - run: dotnet publish programma-exemplum-dotnet.csproj
#       # # ./bin/Release/net5.0/programma-exemplum-dotnet